### ISSUE TITLE
Please add a notifier/callback when a tag gets selected/unselecected

### ISSUE THREAD

**Issue by ajayar** [okq91/TagsLayout#2]
Great library but an interface to alert user when a tag item gets selected would be of great use

**Comment by okq91** [comment]
@ajayar Thank you for your feedback, new release 1.0.3 has been published contains this change.
Please update to implementation 'com.okqapps.tagslayout:tags-layout:1.0.3'
Now you can use tagsLayout.setTagsCallback(this) to get callback when user select/unselect tag item.

**Comment by ajayar** [comment]
Great
